name: pre-commit-autoupdate

on:
  schedule:
  - cron: 12 6 * * 1
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    uses: phc-health/github-workflows/.github/workflows/pre-commit-autoupdate.yml@main
